# DO NOT EDIT THIS FILE -- Reticen8 auto-generated file
{% if helpers.exists('Reticen8.monit.general.enabled') and Reticen8.monit.general.enabled|default("0") == "1" %}
monit_setup="/usr/local/reticen8/scripts/Reticen8/Monit/setup.sh"
monit_enable="YES"
{% else %}
monit_enable="NO"
{% endif %}
